"""fix typo sourse -> source

Revision ID: 4083efcb8940
Revises: fd7be55bd352
Create Date: 2025-09-21 14:58:34.460501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4083efcb8940'
down_revision = 'fd7be55bd352'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=100), nullable=True))
        batch_op.drop_column('sourse')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sourse', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('source')

    # ### end Alembic commands ###
