"""add genre column

Revision ID: 81463fb94779
Revises: 98f33b1939f3
Create Date: 2025-10-02 14:47:13.408004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81463fb94779'
down_revision = '98f33b1939f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('genre')

    # ### end Alembic commands ###
