"""add knowledge and vocabulary columns

Revision ID: c37bae91f382
Revises: 81463fb94779
Create Date: 2025-10-03 06:14:38.753364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c37bae91f382'
down_revision = '81463fb94779'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('knowledge', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('vocabulary', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('vocabulary')
        batch_op.drop_column('knowledge')

    # ### end Alembic commands ###
