"""fix nullable columns

Revision ID: fd7be55bd352
Revises: 
Create Date: 2025-09-20 17:03:43.960321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd7be55bd352'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('publisher', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('sourse', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('sourse')
        batch_op.drop_column('publisher')
        batch_op.drop_column('price')

    # ### end Alembic commands ###
